image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker info | grep Registry

build:
  stage: build
  script:
    - echo Build started on `date` for $CI_COMMIT_REF_NAME
    - if [[ "$CI_COMMIT_REF_NAME" =~ "master" ]]; then export build=latest; else export build=$CI_COMMIT_REF_NAME; fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t richarvey/nginx-php-fpm:"$build" .
    - docker info | grep Registry
    - docker push "$CI_REGISTRY_IMAGE":"$build"
