language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t php .
  - docker run -d -p 127.0.0.1:80:80 --name nginx-php-fpm php

script:
  - docker ps
  - sleep 5
  - curl 127.0.0.1:80
