language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 --name blog blog

script:
  - docker ps | grep -q blog
  - curl 127.0.0.1
