language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t php .
  - docker run -d -p 127.0.0.1:80:80 --name nginx-php-fpm php

script:
  - docker ps | grep -q nginx-php-fpm
  - curl 172.17.0.2
